name: Publish And Deploy
on:
  push: 
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 下载源码
    - name: Checkout
      uses: actions/checkout@master
    # 打包构建
    - name: Build
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run build
    - run: mkdir release
    - run: cp -r .nuxt static nuxt.config.js package.json package-lock.json pm2.config.json ./release


    # 部署到服务器
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.BRUCE_SSH_KEY }} # 服务器的key
          ARGS: '-rltgoDzvO --delete'  #(optional, default '-rltgoDzvO')
          SOURCE: release/ # 这是要复制到服务器的文件夹名称
          REMOTE_HOST: ${{ secrets.HOST }} # 你的服务器公网地址
          REMOTE_USER: ${{ secrets.USERNAME }} # 服务器登录用户名
          TARGET: /Users/wang/projects/realworld-nuxtjs # 放到的目标地址